version: '3.4'

services:
  reportmanagement.api:
    image: ${DOCKER_REGISTRY-}reportmanagementapi
    build:
      context: .
      dockerfile: src/ReportManagement.API/Dockerfile
    environment:
      Mongo__ConnectionString: "mongodb://root:rootpassword@localhost:27017"
      Mongo__DatabaseName: "testdb"
  


  reportmanagement.web:
    image: ${DOCKER_REGISTRY-}reportmanagementweb
    build:
      context: .
      dockerfile: src/ui/ReportManagement.Web/Dockerfile

